.changeset/strange-poems-sin.md, packages/cli/package.json, packages/cli/src/auth.ts, packages/cli/src/i18n.ts, packages/cli/src/services/api-key.ts, packages/cli/src/services/check-auth.ts, packages/cli/src/services/env.ts, packages/cli/src/services/settings.ts, pnpm-lock.yaml
Resolves https://github.com/replexica/replexica/issues/41
=> feat(cli): add `replexica auth` command for easier cli <> api authentication

.changeset/calm-radios-glow.md, demo/classic/json/en.json, demo/classic/json/es.json, packages/cli/src/i18n.ts, packages/cli/src/services/bucket/base.ts, packages/cli/src/services/bucket/core.ts
+ added more data to .json file to see the progress
=> feat: show progress while translating

.changeset/tame-ladybugs-help.md, packages/cli/src/cli/i18n.ts, packages/cli/src/cli/lockfile.ts
=> feat(cli): lockfile autogeneration

.changeset/odd-ducks-heal.md, packages/cli/src/cli/show/files.ts, packages/cli/src/cli/show/index.ts
=> feat(cli): add `replexica show files` cmd #214

i18n.json, readme.md
=> feat: add French support

i18n.json, readme.md
Adding support for german translation for the readme. Wanted to ask whether I have to add the german file manually as well ??
=> feat: add german support

.changeset/tidy-pillows-greet.md, packages/cli/src/cli/i18n.ts, packages/cli/src/cli/show/files.ts, packages/cli/src/cli/show/locale.ts, packages/cli/src/utils/errors.ts, packages/cli/src/workers/auth.ts, packages/cli/src/workers/bucket/android.ts, packages/cli/src/workers/bucket/index.ts, packages/cli/src/workers/bucket/xcode-stringsdict.ts
Fixes: #108
This PR introduces a custom base class for error handling in the CLI, ensuring all errors are consistent and user-friendly. Each error now includes a required documentation link parameter to facilitate troubleshooting and improve usability.
=> feat: standardize error handling in CLI

action/src/flows/in-branch.ts
Checkout correct branch when running GHA in PR context.
=> fix: checkout branch

.changeset/forty-apes-nail.md, packages/cli/src/loaders/index.spec.ts, packages/cli/src/loaders/index.ts, packages/cli/src/loaders/po/index.ts
=> feat(cli): enhance .po loader to support plural translations and improve loader composition

i18n.json
=> feat: add Hindi support 

CONTRIBUTING.md
=> fix(guide): incorrect path to test the cli

.changeset/dull-kiwis-teach.md, packages/cli/src/cli/cmd/i18n.ts
Further filter files targeted by buckets defined in config.
=> feat(cli): add i18n command --file option

.changeset/lazy-flies-draw.md, packages/cli/src/cli/loaders/index.ts, packages/cli/src/cli/loaders/variable/index.ts, packages/spec/src/config.spec.ts
=> fix(cli): po files --frozen flag

.changeset/orange-days-march.md, packages/cli/src/cli/loaders/variable/index.spec.ts, packages/cli/src/cli/loaders/variable/index.ts
=> fix(#780): fix variables ordering mismatch

.changeset/lazy-turkeys-boil.md, packages/cli/src/cli/loaders/csv.ts
=> chore(cli/csv): set `relax_column_count_less: true`

packages/react/src/core/component.tsx
=> chore: refactor template substitution destructive shift() bug

CONTRIBUTING.md
The recent PR #875 added support for Google AI models in the compiler. This PR changes two things:
* Updated CONTRIBUTING.md to include instructions for setting up and using Google AI models
* Added a new section describing how to add new providers
=> feat(contributing): update contributing.md with google ai info and instructions for adding new providers

.changeset/calm-zoos-sit.md, DEBUGGING.md, packages/compiler/src/_const.ts, packages/compiler/src/jsx-fragment.ts, packages/compiler/src/utils/index.ts, packages/compiler/src/utils/invokations.ts
=> fix(compiler): update package import names

.changeset/sharp-cats-leave.md, CONTRIBUTING.md, packages/cli/package.json, packages/cli/src/cli/localizer/explicit.ts, packages/cli/src/cli/processor/index.ts, packages/cli/src/cli/processor/lingo.ts, packages/compiler/package.json, packages/compiler/src/lib/lcp/api/index.ts, packages/compiler/src/lib/lcp/api/provider-details.ts, packages/compiler/src/utils/locales.ts, packages/spec/src/config.ts, pnpm-lock.yaml
=> feat(compiler): ollama ai provider support

i18n.json
=> feat: added polish to read me

.changeset/famous-shrimps-attack.md, package.json, packages/cli/src/cli/cmd/run/execute.ts, packages/cli/src/cli/cmd/run/index.ts, pnpm-lock.yaml
https://www.npmjs.com/package/minimatch
=> feat(cli): match --keys via minimatch in run

.changeset/big-panthers-push.md, demo/react-router-app/app/root.tsx, packages/react/src/client/loader.ts, packages/react/src/client/locale-switcher.tsx, packages/react/src/client/provider.tsx, packages/react/src/client/utils.ts, packages/react/src/core/const.ts, packages/react/src/core/get-dictionary.spec.ts, packages/react/src/core/get-dictionary.ts, packages/react/src/core/index.ts, packages/react/src/react-router/loader.spec.ts, packages/react/src/react-router/loader.ts, packages/react/src/rsc/component.tsx, packages/react/src/rsc/loader.ts, packages/react/src/rsc/provider.tsx, packages/react/src/rsc/utils.ts
For cases:
- no locale
- invalid locale
- unsupported locale
Remove "en" as default locale. Use source locale as default.
=> feat(compiler): fallback to source locale
