lingodotdev/lingo.dev

.changeset/early-fireants-share.md, packages/spec/src/locales.ts
Enable `fr`, `ca` in source+target modes, `cs` (Czech) in source-only mode.
Resolves #63
=> feat: `fr`, `ca`, `cs` locales support

.changeset/tame-timers-jam.md, packages/cli/src/cli/i18n.ts
Resolves #150 
--
cc @quentin-decre
=> fix(cli): Preserve order of JSON keys during localization

.changeset/honest-keys-deliver.md, package/demo/markdown-multi/en/another-blog-post.md, package/demo/markdown-multi/en/blog-post.md, package/demo/markdown-multi/en/ignored-blog-post.md, package/demo/markdown-multi/es/another-blog-post.md, package/demo/markdown-multi/es/blog-post.md, package/i18n.json, package/i18n.lock, packages/cli/src/cli/i18n.ts, packages/cli/src/cli/init.ts, packages/cli/src/workers/config.ts, packages/compiler/src/_utils.ts, packages/compiler/src/config.ts, packages/compiler/src/next.ts, packages/compiler/src/stub.ts, packages/react/src/next/middleware.ts, packages/spec/src/config.spec.ts, packages/spec/src/config.ts
Major upgrade:
`i18n.json` now supports file exclusions. Here's how:
```json
"buckets": {
"markdown": {
"include": [
"demo/markdown-multi/[locale]/*.md",
"demo/markdown/[locale].md"
],
"exclude": [
"demo/markdown-multi/[locale]/ignored-blog-post.md"
]
}
},
```
Key changes:
1. Bucket type (i.e. `markdown`, `json`, etc) is now the *key* in the `buckets` object map.
2. Each bucket configuration node has two fields: `include` (required) and `exclude` (optional).
Example: Despite `ignored-blog-post.md` matching the `demo/markdown-multi/[locale]/*.md` pattern, `replexica i18n` ignores it due to the `exclude` field entry.
--
Resolves #151
=> feat(spec): exclusion patterns

.changeset/red-books-complain.md, packages/cli/src/cli/i18n.ts, packages/cli/src/cli/index.ts, packages/cli/src/cli/init.ts, packages/cli/src/cli/lockfile.ts, packages/cli/src/workers/lockfile.ts
Adding `replexica lockfile` command, to simplify initial onboarding for user who's already got some translation files in place.
Resolves #120
=> feat(cli): add `replexica lockfile` for explicit lockfile generation

.changeset/nasty-buttons-act.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
This PR resolves #112 , and it implements 2 new github issue forms which can help any user to create new issues the repository in a easier and more defined way
Screenshots:
Feature-request:
Bug-report:
=> feat: Added 2 new github issue templates

.github/workflows/pr-check.yml, .github/workflows/release.yml
This PR introduces a new feature in custom GitHub Action that allows developers to bypass Github action workflows by including the string '[skip i18n]' in their commit message, enabling teams to quickly skip i18n checks as needed.
This pr adds the skip to the pr-check and release workflows tell me if u want to do that for the pr-lint workflow as well ;D
=> #192 feat:Action skip on commit message contains '[skip i18n]'

.changeset/shaggy-beans-whisper.md, packages/cli/src/cli/i18n.ts, packages/spec/src/config.spec.ts, packages/spec/src/config.ts
Fixes: #198 
This PR modifies the CLI to prevent overwriting i18n.json with a default template when an unsupported locale is provided. Instead of allowing the file to be overwritten, the CLI now checks for unsupported locales and throws a clear error message if one is detected.
=> fix: prevent overwriting i18n.json for unsupported locales

.changeset/fuzzy-feet-buy.md, packages/cli/src/cli/i18n.ts
Ensures that the --frozen flag exits before entering the localization loop if lockfile changes are detected, preventing unnecessary processing and API calls. Useful for CI/CD workflows to check localization changes.
Closes #110
=> fix(cli): add early exit for --frozen flag if lockfile update required

.changeset/rude-emus-retire.md, packages/spec/src/config.spec.ts, packages/spec/src/locales.ts
Support [language codes](https://en.wikipedia.org/wiki/IETF_language_tag) with underscore, format used by eg. [Flutter apps](https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization).
=> feat: support underscore in locale code

.changeset/dirty-phones-exist.md, action.yml, action/src/platforms/_base.ts, legacy/cli/bin/cli.mjs, packages/cli/src/cli/cli/auth.ts, packages/cli/src/cli/utils/settings.ts
Warning in the old package, if it detects new config (new variable name present in env):
```
⚠️  WARNING: NEW PACKAGE AVAILABLE ⚠️
================================================================================
This CLI version is deprecated.
This version is not compatible with LINGODOTDEV_API_KEY env variable.
Please use lingo.dev instead:
npx lingo.dev@latest
Visit https://lingo.dev for more information.
================================================================================
```
Warning in the new package, if it detects old config (old variable name present in env, new variable name not present):
```
⚠️  WARNING: REPLEXICA_API_KEY env var is deprecated ⚠️
===========================================================
Please use LINGODOTDEV_API_KEY instead. …
```
=> chore: map old env vars in legacy package

.changeset/few-trains-pay.md, packages/cli/package.json, packages/cli/src/cli/loaders/flat.spec.ts, packages/cli/src/cli/loaders/flat.ts, packages/cli/src/cli/loaders/index.spec.ts
Flat loader remembers which sections were object and arrays on pull. It reconstructs original object on push. Loader preserves its local state between pulls.
=> fix: transform object with numeric keys

action.yml, action/src/flows/in-branch.ts, action/src/platforms/_base.ts, packages/cli/src/cli/cmd/i18n.ts
If you have a complex CI/CD setup you may want to run the action even on commits by this action. It will still result in no changes in most cases, but it will still check for changes (takes longer to run the action).
=> feat(action): process commits by this action

action/src/platforms/github.ts
To process commits by this action it needs to re-trigger the CI. This is achieved by using personal access token (PAT) instead of the default GITHUB_TOKEN provided by the action.
Also needs to explicitly set `persist-credentials: false` on checkout step.
=> feat(action): use provided GH token

.changeset/brave-beans-mix.md, packages/cli/src/cli/cmd/init.ts, packages/cli/src/cli/loaders/index.spec.ts, packages/cli/src/cli/loaders/index.ts, packages/cli/src/cli/loaders/vue-json.ts, packages/cli/src/cli/utils/find-locale-paths.spec.ts, packages/cli/src/cli/utils/find-locale-paths.ts, packages/spec/src/formats.ts
New bucket type `vue-json` to translation message from [Vue I18n](https://kazupon.github.io/vue-i18n/guide/sfc.html#basic-usage).
Running locally:
1. initialize
```
node ../lingo.dev/packages/cli/bin/cli.mjs init --source en --targets es --bucket vue-json
```
2. translate
```
node ../lingo.dev/packages/cli/bin/cli.mjs i18n
```
=> feat(cli): support JSON messages in <i18n> block of .vue files

.changeset/weak-jobs-shave.md, packages/sdk/src/index.ts
Lingo.dev will automatically detect the language of supplied content. Localization requests with language detection will take longer compared to passing explicit `sourceLocale`.
=> feat(sdk): support `null` value for `sourceLocale`

.changeset/dry-items-applaud.md, packages/cli/src/cli/utils/settings.ts
Only warn when there is API key in  `.lingodotdevrc` to avoid warnings in CI env.
=> feat(cli): warn if env vars override values from "auth --login"

.changeset/flat-emus-hunt.md, packages/cli/src/cli/loaders/prettier.ts
1. try to run prettier (if there are no plugins it will run correctly on first try)
2. if it fails to run install all project dependencies (in order to use package manager lock file)
3. try to run again (if the issue was with missing dependencies, it will run correctly this time)
It does not affect prettier configurations without plugins.
=> feat(cli): support prettier plugins

.changeset/warm-actors-confess.md, action/package.json, action/src/index.ts, action/src/main.d.ts, action/src/main.ts, action/src/platforms/bitbucket.ts, action/src/platforms/github.ts, action/src/platforms/gitlab.ts, action/tsconfig.json, packages/cli/package.json, packages/cli/src/cli/cmd/ci.ts, packages/cli/src/cli/index.ts, pnpm-lock.yaml
Execute CI/CD action via `npx lingo.dev ci`
=> feat(cli): add "ci" command

.changeset/strange-insects-greet.md, packages/cli/src/cli/cmd/cleanup.ts, packages/cli/src/cli/cmd/i18n.ts, packages/cli/src/cli/cmd/lockfile.ts, packages/cli/src/cli/cmd/show/files.ts, packages/cli/src/cli/loaders/index.spec.ts, packages/cli/src/cli/loaders/index.ts, packages/cli/src/cli/loaders/inject-locale.ts, packages/cli/src/cli/utils/buckets.spec.ts, packages/cli/src/cli/utils/buckets.ts, packages/spec/src/config.ts
Add array of keys as "injectLocale" to JSON bucket config.
Example:
```json
{
"version": 1.4,
"locale": {
"source": "en",
"targets": [
"es", 
"sk"
]
},
"buckets": {
"json": {
"include": [
"locales/[locale].json"
],
"injectLocale": [
"settings.locale",
"language"
]
}
},
"$schema": "https://lingo.dev/schema/i18n.json"
}
```
This config will replace `settings.locale` and `langauge` values with `es` and `sk` values if the original value in source file was `en`.
=> feat(cli): inject locale code into locale files

.changeset/calm-mugs-cheat.md, packages/cli/src/cli/loaders/prettier.ts
When installing prettier plugins, use `bun` package manager if project uses it (https://bun.sh/).
=> feat(cli): support bun package manager

.changeset/smart-cobras-appear.md, packages/spec/src/locales.spec.ts, packages/spec/src/locales.ts
- **Added Georgian (ka-GE) locale support:**
- Extended `localeMap` in `packages/spec/src/locales.ts` to include Georgian locale
- Added corresponding test case in `packages/spec/src/locales.spec.ts` for `getLocaleCodeDelimiter`
- Closes #750 
- No breaking changes introduced
- All tests are passing with the new locale addition
- As I talked with @maxprilutskiy on X (Twitter) seems like this is the first step for the API to have support for the Gregorian Language
=> feat: add georgian (ka-GE) locale support

.changeset/funny-cars-confess.md, packages/cli/demo/csv/file.csv, packages/cli/src/cli/loaders/csv.ts, packages/cli/src/cli/loaders/index.spec.ts
This PR is a set of changes for `csv` loader:
+ Reduce duplicated parsing
+ Dynamic key column naming support
* Resolves #870
I added some variables like `inputParsed` to prevent parsing twice in both `pull` and `push`
I added a local function `_detectKeyColumnName()` to automatically detect the key column naming, current logics including: `known preferred keys` (`KEY`|`key`), `first non-empty cell`.
At first I was working on another solution where I deprecate `id` (and still supports it for backward-compat), and prefers `KEY`, and adding a whole new option to set the `keyColumn`, but they requires too big of a change, I then followed @maxprilutskiy's suggestion of looking at `[0]`, its simpler and works too I guess, could be breaking for those who is using the old `id` naming in a …
=> feat(cli/csv): improve `csv` loader

.changeset/silly-cows-own.md, packages/compiler/src/_base.ts, packages/compiler/src/_utils.ts, packages/compiler/src/client-dictionary-loader.ts, packages/compiler/src/index.ts, packages/compiler/src/jsx-attribute-scope-inject.spec.ts, packages/compiler/src/jsx-attribute-scope-inject.ts, packages/compiler/src/jsx-attribute-scopes-export.ts, packages/compiler/src/jsx-scope-inject.spec.ts, packages/compiler/src/jsx-scope-inject.ts, packages/compiler/src/jsx-scopes-export.ts, packages/compiler/src/react-router-dictionary-loader.ts, packages/compiler/src/rsc-dictionary-loader.ts
* inject relative paths instead of `@/` mapped paths
* renamed `fileKey` to be `relativeFilePath` as a hint that the field is expected to contain a relative path
=> fix(compiler): rm `@/` and `~/` path mappings

.changeset/breezy-pumas-fix.md, packages/cli/src/cli/utils/buckets.ts
This PR fixes an issue where lingo.dev status and lingo.dev run could not correctly resolve file paths on Windows environments.
- Add helper function for path normalization on Windows platform
- Use normalized paths when validating path patterns
- Convert glob patterns to Unix-style for Windows compatibility
- Normalize returned paths to ensure cross-platform compatibility
discord thread: https://discord.com/channels/1193198600298172486/1382888601494356048
=> fix(cli): normalize paths and improve compatibility on windows

.changeset/fuzzy-mice-heal.md, packages/compiler/package.json, packages/compiler/src/_base.ts, pnpm-lock.yaml
This PR attempts to improve the type-safety of the `CompilerParams` type:
- set `sourceLocale` to `LocaleCode` instead of `string`
- set `targetLocale` to `LocaleCode` instead of `string`
- require the locale pairings in the `models` property to match one of the following formats:
- `locale:locale`
- `*:locale`
- `locale:*`
- `*:*`
- require the model identifier to be a colon separated string (e.g., `string:string`)
The model identifier can definitely be typed better — I'm imagining constructing a type of exact providers and models — but that's a bigger task.
=> feat: improve type-safety of CompilerParams

.changeset/large-zoos-explain.md, packages/compiler/src/utils/jsx-content-whitespace.spec.ts, packages/compiler/src/utils/jsx-content.ts
fixes #984 
This pull request introduces improvements to whitespace normalization in JSX content handling within the Lingo.dev compiler. The key changes include refining the logic for preserving meaningful whitespace, adding targeted tests to ensure correctness, and cleaning up debug files. These updates enhance the robustness of JSX whitespace handling and improve code maintainability.
* Improved the `normalizeJsxWhitespace` function to distinguish between formatting whitespace and meaningful leading/trailing spaces, ensuring proper preservation and collapsing of spaces as needed. Added handling for single-line and multi-line content separately. (`packages/compiler/src/utils/jsx-content.ts`, [packages/compiler/src/utils/jsx-content.tsR129-R184](diffhunk://#diff-c221deb69b53a09b21cfe5551de …
=> fix(compiler): fix remove whitespaces from inside the element

.changeset/large-beds-cover.md, packages/cli/src/cli/constants.ts, packages/cli/src/cli/utils/ui.ts
fix : Make run cmd in CLI print a list of collected errors
Summary:
Should close https://github.com/lingodotdev/lingo.dev/issues/989
Added the changes in the ui.ts file as mentioned in the design notes in the issue to display the collected errors
Screenshot of the changes:
=> fix(cli): make run cmd in CLI print a list of collected errors

.changeset/young-bees-glow.md, packages/compiler/src/jsx-fragment.spec.ts, packages/compiler/src/utils/index.ts
This PR fixes cases where an app includes `import * as React from "react"` and the compiler tries to `import * as React, { Fragment } from "react"`, which causes an error.
This is now fixed by using the namespace import (`React.Fragment`), as is appropriate.
The PR also correctly uses `React.Fragment` when React is imported as a default import.
=> feat(compiler): fix `import * as React from "react"` edge cases in compiler

packages/cli/package.json, packages/cli/src/locale-codes/index.ts, packages/cli/tsup.config.ts, pnpm-lock.yaml
- Adds `lingo.dev/locale-codes` export to make the locale parsing and validation utilities available to users
- Follows the existing re-export pattern used by other packages (sdk, spec, compiler, react)
- Added `@lingo.dev/_locales` as a workspace dependency to the CLI package
- Created `src/locale-codes/index.ts` re-export file following the symmetric pattern
- Updated `package.json` with locale-codes export configuration
- Updated `tsup.config.ts` to build the locale-codes entry point
Users can now import locale utilities directly:
```typescript
import { parseLocale, isValidLocale, getCountryName } from "lingo.dev/locale-codes";
```
Closes P-283
=> feat: add locale-codes export to CLI package

.changeset/brown-vans-bow.md, packages/cli/src/cli/loaders/formatters/biome.ts
The bug is specifically in how the JS API v3 handles configuration serialization/deserialization when certain properties like $schema, vcs, and files are present. 
Applied workaround filters out those properties - we're avoiding the buggy code path in the JS API while the CLI never encounters this issue in the first place.
(The Biome CLI doesn't have this issue because it uses a completely different, more direct code path written in Rust.)
=> fix: biome JS API v3 bug
